spring.application.name=shopwave-monolith

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5433/shopwave
spring.datasource.username=shopwave
spring.datasource.password=shopwave
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6380

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Actuator / Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
